import type { Metadata } from "next";

import AppProvider from "@/app/providers/app-provider";
import Footer from "@/components/footer/footer";
import NavigationBar from "@/components/navbar/navbar";
import { abyssinica_sil, afacad } from "@/components/theme/fonts";

export const metadata: Metadata = {
  title: "Wastevest Technologies",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      // className={`${abyssinica_sil.className} ${afacad.className}`}
    >
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin="anonymous"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Abyssinica+SIL&family=Afacad:ital,wght@0,400..700;1,400..700&display=swap"
          rel="stylesheet"
        />
      </head>
      <body>
        <AppProvider>
          {/* <NavigationBar /> */}
          {children}
          <Footer />
        </AppProvider>
      </body>
    </html>
  );
}
