import type { Metadata } from "next";

import AppProvider from "@/app/providers/app-provider";
import Footer from "@/components/footer/footer";
import NavigationBar from "@/components/navbar/navbar";
import { abyssinica_sil, afacad } from "@/components/theme/font";

export const metadata: Metadata = {
  title: "Wastevest Technologies",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={`${abyssinica_sil.className} ${afacad.className}`}
    >
      <body>
        <AppProvider>
          {/* <NavigationBar /> */}
          {children}
          <Footer />
        </AppProvider>
      </body>
    </html>
  );
}
